const typingText='Selamat Anniversary ke-3, sayangggg.❤️';let i=0;
function type(){const el=document.getElementById('typing');if(i<typingText.length){el.innerHTML+=typingText.charAt(i++);setTimeout(type,65)}}type();
function enterUniverse(){document.getElementById('intro').classList.add('hidden');document.getElementById('main').classList.remove('hidden');const music=document.getElementById('music');music.volume=.28;music.play().catch(()=>showToast('Tambahkan music.mp3 ke folder assets jika ingin musik 🎵'));window.scrollTo(0,0);for(let j=0;j<18;j++)setTimeout(createHeart,j*90)}
function showToast(text){const t=document.getElementById('toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
function sendHug(){showToast('Peluk virtual terkirim untuk sayanggg🤍');for(let j=0;j<30;j++)setTimeout(createHeart,j*65)}
const reasons={1:'Karena sayanggg selalu punya cara membuat hariku terasa lebih tenang.',2:'Karena senyummu sederhana, tapi selalu berhasil memperbaiki hariku.',3:'Karena bersamamu, tempat biasa pun bisa terasa seperti rumah.',4:'Karena sayanggg membuat hal-hal kecil terasa begitu berharga.',5:'Karena sayanggg membuatku ingin terus menjadi versi terbaik dari diriku.',6:'Karena setelah semua yang kita lewati, hatiku masih memilih sayanggg.'};
function showReason(n){document.getElementById('reasonText').textContent=reasons[n]}
function openLetter(){const l=document.getElementById('letter');l.classList.toggle('hidden');if(!l.classList.contains('hidden'))l.scrollIntoView({behavior:'smooth',block:'center'})}
function secretMessage(){showToast('Kalau harus memilih lagi, sa tetap memilih sayangggg. Setiap hari.❤️');for(let j=0;j<70;j++)setTimeout(createHeart,j*40)}
function updateCount(){const start=new Date('2023-08-18T00:00:00');const now=new Date();let diff=Math.max(0,now-start);const day=86400000,hour=3600000,min=60000;const days=Math.floor(diff/day);diff-=days*day;const hours=Math.floor(diff/hour);diff-=hours*hour;const minutes=Math.floor(diff/min);const seconds=Math.floor((diff-minutes*min)/1000);document.getElementById('countup').innerHTML=`<span>${days} Hari</span><span>${hours} Jam</span><span>${minutes} Menit</span><span>${seconds} Detik</span>`}setInterval(updateCount,1000);updateCount();
function createHeart(){const h=document.createElement('div');h.className='heart';h.textContent=Math.random()>.45?'♡':'✦';h.style.left=Math.random()*100+'vw';h.style.fontSize=14+Math.random()*24+'px';h.style.animationDuration=4+Math.random()*5+'s';document.getElementById('hearts').appendChild(h);setTimeout(()=>h.remove(),9000)}setInterval(createHeart,1200);
